name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'data.json'
      - '.github/README-template.j2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install jinja2
        run: sudo pip install jinja2
      - name: Build
        run: python3 .github/scripts/render-readme.py
      - name: Check if file changed
        id: changedCheck
        continue-on-error: true
        run: git diff --exit-code README.md
      - name: Commit
        if: steps.changedCheck.outcome == 'failure'
        run: |
          git config --global user.name 'Shmavon Gazanchyan'
          git config --global user.email 'MunGell@users.noreply.github.com'
          git commit -am "Update README.md"
          git push
